# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 09:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_blog', '0002_auto_20170714_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
