# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_blog', '0003_post_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_time',
            field=models.DateField(auto_now_add=True, verbose_name='创建日期'),
        ),
    ]
