# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-07-16 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('office_blog', '0004_auto_20170714_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='bady',
            new_name='body',
        ),
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200, verbose_name='简介'),
        ),
    ]
